### ISSUE TITLE
Unable to see mod related info

### ISSUE THREAD

**Issue by gamerpotion** [RelativityMC/unsafe-world-random-access-detector#2]
Hi, im using this mod currently on our server, 
recently been getting a lot of these errors in console, but am unable to tell the mod responsible for these outputs?

```[10.05 12:49:30] [Server] [Server thread/INFO]: There are 9 of a max of 30 players online: GrizzlyFolk, zeybekege, BeBeBerry, EGARudder, Jandrew92, LordBirdmann, Lucina_, CrackerCrusader, Cirieto
[10.05 12:49:34] [Server] [Worker-Main-6/ERROR]: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: Worker-Main-6)
[10.05 12:49:34] [Server] Possible solutionsFind possible causes in the stack trace below and report to the corresponding mod authors 
[10.05 12:49:34] [Server] java.util.ConcurrentModificationExceptionThreadLocalRandom accessed from a different thread (owner: Server thread, current: Worker-Main-6)
[10.05 12:49:34] [Server] 	at com.ishland.uwrad.common.CheckedThreadLocalRandom.handleNotOwner(CheckedThreadLocalRandom.java:51) ~[unsafe-world-random-access-detector-1.1.0.jar:?]
[10.05 12:49:34] [Server] 	at com.ishland.uwrad.common.CheckedThreadLocalRandom.isSafe(CheckedThreadLocalRandom.java:38) ~[unsafe-world-random-access-detector-1.1.0.jar:?]
[10.05 12:49:34] [Server] 	at com.ishland.uwrad.common.CheckedThreadLocalRandom.method_43156(CheckedThreadLocalRandom.java:82) ~[unsafe-world-random-access-detector-1.1.0.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_6566.method_43048(class_6566.java:33) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_4466$class_4472.<init>(class_4466.java:854) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_4466.method_5959(net/minecraft/class_4466.java:216) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_1308.<init>(net/minecraft/class_1308.java:149) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_1314.<init>(class_1314.java:14) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_1296.<init>(net/minecraft/class_1296.java:28) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_1429.<init>(net/minecraft/class_1429.java:42) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_4466.<init>(net/minecraft/class_4466.java:175) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_1299.method_5883(net/minecraft/class_1299.java:535) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_1299.method_17846(net/minecraft/class_1299.java:539) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at java.util.Optional.map(Optional.java:260) ~[?:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_1299.method_5892(net/minecraft/class_1299.java:539) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3499.method_17916(net/minecraft/class_3499.java:424) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3499.method_15179(net/minecraft/class_3499.java:409) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3499.method_15172(net/minecraft/class_3499.java:349) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3781.method_16626(class_3781.java:122) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3790.method_27236(net/minecraft/class_3790.java:89) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3790.method_14931(net/minecraft/class_3790.java:85) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3449.method_14974(class_3449.java:100) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_2794.method_38265(net/minecraft/class_2794.java:320) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_2794.method_12102(net/minecraft/class_2794.java:319) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_2806.method_20613(class_2806.java:146) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_2806.method_12154(class_2806.java:293) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3898.method_17225(net/minecraft/class_3898.java:689) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3898.method_17224(net/minecraft/class_3898.java:683) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
[10.05 12:49:34] [Server] 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3846.run(class_3846.java:102) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
[10.05 12:49:34] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
[10.05 12:49:34] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
[10.05 12:49:34] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
[10.05 12:49:34] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
[10.05 12:49:34] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[10.05 12:49:34] [Server] [Worker-Main-6/ERROR]: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: Worker-Main-6)
[10.05 12:49:34] [Server] Possible solutionsFind possible causes in the stack trace below and report to the corresponding mod authors 
[10.05 12:49:34] [Server] java.util.ConcurrentModificationExceptionThreadLocalRandom accessed from a different thread (owner: Server thread, current: Worker-Main-6)
[10.05 12:49:34] [Server] 	at com.ishland.uwrad.common.CheckedThreadLocalRandom.handleNotOwner(CheckedThreadLocalRandom.java:51) ~[unsafe-world-random-access-detector-1.1.0.jar:?]
[10.05 12:49:34] [Server] 	at com.ishland.uwrad.common.CheckedThreadLocalRandom.isSafe(CheckedThreadLocalRandom.java:38) ~[unsafe-world-random-access-detector-1.1.0.jar:?]
[10.05 12:49:34] [Server] 	at com.ishland.uwrad.common.CheckedThreadLocalRandom.method_43156(CheckedThreadLocalRandom.java:82) ~[unsafe-world-random-access-detector-1.1.0.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_6566.method_43048(class_6566.java:33) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_4466$class_4472.<init>(class_4466.java:854) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_4466.method_5959(net/minecraft/class_4466.java:216) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_1308.<init>(net/minecraft/class_1308.java:149) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_1314.<init>(class_1314.java:14) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_1296.<init>(net/minecraft/class_1296.java:28) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_1429.<init>(net/minecraft/class_1429.java:42) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_4466.<init>(net/minecraft/class_4466.java:175) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_1299.method_5883(net/minecraft/class_1299.java:535) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_1299.method_17846(net/minecraft/class_1299.java:539) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at java.util.Optional.map(Optional.java:260) ~[?:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_1299.method_5892(net/minecraft/class_1299.java:539) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3499.method_17916(net/minecraft/class_3499.java:424) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3499.method_15179(net/minecraft/class_3499.java:409) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3499.method_15172(net/minecraft/class_3499.java:349) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3781.method_16626(class_3781.java:122) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3790.method_27236(net/minecraft/class_3790.java:89) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3790.method_14931(net/minecraft/class_3790.java:85) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3449.method_14974(class_3449.java:100) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_2794.method_38265(net/minecraft/class_2794.java:320) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_2794.method_12102(net/minecraft/class_2794.java:319) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_2806.method_20613(class_2806.java:146) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_2806.method_12154(class_2806.java:293) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3898.method_17225(net/minecraft/class_3898.java:689) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3898.method_17224(net/minecraft/class_3898.java:683) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
[10.05 12:49:34] [Server] 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_3846.run(class_3846.java:102) ~[server-intermediary.jar:?]
[10.05 12:49:34] [Server] 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
[10.05 12:49:34] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
[10.05 12:49:34] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
[10.05 12:49:34] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
[10.05 12:49:34] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
[10.05 12:49:34] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[10.05 12:49:34] [Server] [Worker-Main-6/ERROR]: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: Worker-Main-6)
[10.05 12:49:34] [Server] Possible solutionsFind possible causes in the stack trace below and report to the corresponding mod authors 
[10.05 12:49:34] [Server] java.util.ConcurrentModificationExceptionThreadLocalRandom accessed from a different thread (owner: Server thread, current: Worker-Main-6)
[10.05 12:49:34] [Server] 	at com.ishland.uwrad.common.CheckedThreadLocalRandom.handleNotOwner(CheckedThreadLocalRandom.java:51) ~[unsafe-world-random-access-detector-1.1.0.jar:?]
[10.05 12:49:34] [Server] 	at com.ishland.uwrad.common.CheckedThreadLocalRandom.isSafe(CheckedThreadLocalRandom.java:38) ~[unsafe-world-random-access-detector-1.1.0.jar:?]
[10.05 12:49:34] [Server] 	at com.ishland.uwrad.common.CheckedThreadLocalRandom.method_43156(CheckedThreadLocalRandom.java:82) ~[unsafe-world-random-access-detector-1.1.0.jar:?]
[10.05 12:49:34] [Server] 	at net.minecraft.class_6566.method_43048(class_6566.java:33) ~[server-intermediary.jar:?]```

**Comment by ishland** [comment]
This indicates a mod or datapack is spawning bee entities (not bee hives) during worldgen. Bees are not safe to spawn during worldgen. 

Unfortunately the bee is spawned through vanilla worldgen pipeline so you'll have to find the source yourself.

**Comment by gamerpotion** [comment]
Thank you @ishland   your mod is great! 
I have been in contact with Terralith creators who said they will be switching to hives method.
